POST http://mos-sage.local/wp-json/mos-affiliate/v1/clickbank-ins
Content-Type: application/json
Accept: application/json

{
  "transactionTime": "20201117T113225-0800",
  "receipt": "authority_bonuses_test",
  "transactionType": "RFND",
  "vendor": "superaa",
  "affiliate": "authority-bonuses-sponsor-test",
  "role": "VENDOR",
  "totalAccountAmount": -81.5499999999999971578290569595992565155029296875,
  "paymentMethod": "PYPL",
  "totalOrderAmount": -197,
  "totalTaxAmount": 0,
  "totalShippingAmount": 0,
  "currency": "USD",
  "orderLanguage": "EN",
  "lineItems": [
    {
      "itemNo": "53",
      "productTitle": "Ultimate Authority Bonuses",
      "shippable": false,
      "recurring": false,
      "accountAmount": -81.5499999999999971578290569595992565155029296875,
      "quantity": 1,
      "downloadUrl": "https:\/\/myonlinestartup.com\/partnerthanks?item=100&cbreceipt=PZ426A3B&time=1604604711&cbpop=DC2E905C&cbaffi=ITSBRIANP&cname=Robert+Serynek&cemail=rdsmgsals%40gmail.com&ccountry=US&czip=95843&cbitems=100&email=biz4robert68@gmail.com&mos_email=biz4robert68@gmail.com&wpid=443148&mos_wpid=443148&mos_username=Rdsmgs&mos_sponsor=itsbrianp&mos_name=Robert",
      "lineItemType": "ORIGINAL",
      "productPrice": -197,
      "productDiscount": 0,
      "affiliatePayout": -99.6700000000000017053025658242404460906982421875,
      "taxAmount": 0,
      "shippingAmount": 0,
      "shippingLiable": false
    }
  ],
  "customer": {
    "shipping": {
      "firstName": "John",
      "lastName": "Smith",
      "fullName": "John Smith",
      "email": "martin.g.cao@gmail.com",
      "address": {}
    },
    "billing": {
      "firstName": "John",
      "lastName": "Smith",
      "fullName": "John Smith",
      "email": "martin.g.cao@gmail.com",
      "address": {}
    }
  },
  "version": 7,
  "attemptCount": 2,
  "vendorVariables": {
    "cbitems": "1000",
    "customer_wpid": "1",
    "customer_username": "martingcao",
    "customer_name": "John Smith",
    "customer_email": "martin.g.cao@gmail.com",
    "sponsor_wpid": "1",
    "sponsor_username": "martingcao",
    "sponsor_name": "John Smith",
    "sponsor_email": "martin.g.cao@gmail.com",
    "campaign": "rfnd_authority_bonuses_test"
  }
}